### ISSUE TITLE
module must have its parameters and buffers on device cuda:0 (device_ids[0]) but found one of them on device: cuda:1

### ISSUE THREAD

**Issue by bo-wang-up** [kamata1729/FullySpikingVAE#1]
I run the code on cuda:1. 

But when the code executes the "calc_clean_fid(net, e)", the code will report the "RuntimeError: module must have its parameters and buffers on device cuda:0 (device_ids[0]) but found one of them on device: cuda:1"

**Comment by kamata1729** [comment]
Thank you for reporting the error.
Can you give me a more detailed location on the implementation code where the error occurred?

**Comment by bo-wang-up** [comment]
compute FID of a model with mnist_test-1024 statistics
FID model:   0%|                                                                                                                                                                              | 0/20 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "main_fsvae.py", line 335, in <module>
    calc_clean_fid(net, e)
  File "main_fsvae.py", line 206, in calc_clean_fid
    fid_score = clean_fid.get_clean_fid_score(network, glv.network_config['dataset'], init_device, num_gen)
  File "/home/wangbo/codes/FullySpikingVAE/metrics/clean_fid.py", line 28, in get_clean_fid_score
    score = fid.compute_fid(gen=sample_from_vae, dataset_name=dataset_name,
  File "/home/wangbo/anaconda3/envs/pytorch/lib/python3.8/site-packages/cleanfid/fid.py", line 525, in compute_fid
    score = fid_model(gen, dataset_name, dataset_res, dataset_split,
  File "/home/wangbo/anaconda3/envs/pytorch/lib/python3.8/site-packages/cleanfid/fid.py", line 251, in fid_model
    np_feats = get_model_features(G, model, mode=mode,
  File "/home/wangbo/anaconda3/envs/pytorch/lib/python3.8/site-packages/cleanfid/fid.py", line 228, in get_model_features
    feat = get_batch_features(resized_batch, model, device)
  File "/home/wangbo/anaconda3/envs/pytorch/lib/python3.8/site-packages/cleanfid/fid.py", line 88, in get_batch_features
    feat = model(batch.to(device))
  File "/home/wangbo/anaconda3/envs/pytorch/lib/python3.8/site-packages/cleanfid/features.py", line 25, in model_fn
    def model_fn(x): return model(x)
  File "/home/wangbo/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/wangbo/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 157, in forward
    raise RuntimeError("module must have its parameters and buffers "
RuntimeError: module must have its parameters and buffers on device cuda:0 (device_ids[0]) but found one of them on device: cuda:1

**Comment by 1439278026** [comment]
Do you solve the problem？
I met the same problem as you on cuda：9

**Comment by bo-wang-up** [comment]
> Do you solve the problem？ I met the same problem as you on cuda：9

Sorry, I didn't solve it. What about you?
